# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meta_description',
            field=models.CharField(max_length=255, verbose_name='Meta Keywords Description'),
        ),
    ]
