# Generated by Django 2.1.2 on 2018-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youraddress', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
    ]
