# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 22:29
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='GMT'),
        ),
    ]
