# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180217_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
