# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20180302_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
