# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20180302_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
